#!/usr/bin/env node
/**
 * AutoLaravel CLI setup script
 * Installs the `artisan` command so it works from anywhere in Git Bash / Unix shells.
 *
 * Called automatically after Composer generates the project autoloader.
 * Can also be run manually: node .auto/setup.js
 */

import { writeFileSync, readFileSync, chmodSync, mkdirSync, existsSync, accessSync, constants } from 'node:fs';
import { resolve, dirname, delimiter } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir } from 'node:os';

const __dir   = dirname(fileURLToPath(import.meta.url));
const cliPath = resolve(__dir, 'cli.js');

// ── Find node executable ──────────────────────────────────────────────────────
// ── Build the artisan shell script content ────────────────────────────────────
// Use a POSIX sh script so it works in Git Bash, WSL, and Linux/macOS
const scriptContent = `#!/usr/bin/env sh
# artisan – AutoLaravel CLI
# Auto-generated by .auto/setup.js
project_dir="$PWD"

while :; do
    if [ -f "$project_dir/.auto/cli.js" ]; then
        exec node "$project_dir/.auto/cli.js" "$@"
    fi

    parent_dir=$(dirname "$project_dir")
    if [ "$parent_dir" = "$project_dir" ]; then
        break
    fi
    project_dir="$parent_dir"
done

printf '%s\\n' 'artisan: no AutoLaravel project found in this directory or its parents.' >&2
exit 1
`;

// ── Determine install targets ─────────────────────────────────────────────────
const home    = homedir();
const pathEntries = (process.env.PATH ?? '')
    .split(delimiter)
    .filter(Boolean)
    .map((entry) => resolve(entry));
const pathKeys = new Set(pathEntries.map((entry) => process.platform === 'win32' ? entry.toLowerCase() : entry));
const composerHome = process.env.COMPOSER_HOME
    ?? (process.platform === 'win32'
        ? resolve(process.env.APPDATA ?? resolve(home, 'AppData', 'Roaming'), 'Composer')
        : resolve(process.env.XDG_CONFIG_HOME ?? resolve(home, '.config'), 'composer'));
const composerBin = resolve(process.env.COMPOSER_BIN_DIR ?? resolve(composerHome, 'vendor', 'bin'));
const npmBin = process.platform === 'win32'
    ? resolve(process.env.APPDATA ?? resolve(home, 'AppData', 'Roaming'), 'npm')
    : null;

// Bare `artisan` only works when its directory is already on PATH. Prefer the
// Composer global bin (the normal home for Composer-installed CLI tools), then
// npm's global bin and conventional user bins when they are already on PATH.
const candidates = [composerBin, npmBin, resolve(home, 'bin'), resolve(home, '.local', 'bin')]
    .filter(Boolean)
    .map((directory) => resolve(directory))
    .filter((directory, index, all) => all.indexOf(directory) === index)
    .filter((directory) => pathKeys.has(process.platform === 'win32' ? directory.toLowerCase() : directory));

const targets = [];
for (const directory of candidates) {
    try {
        if (!existsSync(directory)) mkdirSync(directory, { recursive: true });
        accessSync(directory, constants.W_OK);
        targets.push(resolve(directory, 'artisan'));
    } catch {
        // Continue to another already-PATH'd, user-writable bin directory.
    }
}

let installed = false;

for (const target of targets) {
    try {
        if (existsSync(target)) {
            const existing = readFileSync(target, 'utf8');
            if (!existing.includes('AutoLaravel CLI')) {
                console.warn(`[auto] Skipping existing command: ${target}`);
                continue;
            }
        }

        writeFileSync(target, scriptContent, { encoding: 'utf8' });
        chmodSync(target, 0o755);

        console.log(`[auto] artisan installed → ${target}`);
        installed = true;
    } catch (err) {
        // Silent — try next target
    }
}

if (!installed) {
    console.warn('[auto] Could not install artisan in a writable directory already on PATH.');
    console.warn('[auto] Ensure Composer global bin is on PATH, then run composer install again.');
    console.warn('[auto] Run manually:');
    console.warn(`[auto]   node "${cliPath.replace(/\\/g, '/')}" <command>`);
} else {
    console.log('[auto] Setup complete. Run: artisan dev');
}
