#!/usr/bin/env node
/**
 * davingm CLI setup script
 * Installs the `artisan` command so it works from anywhere in Git Bash / Unix shells.
 *
 * Called automatically by composer post-create-project-cmd.
 * Can also be run manually: node .davingm/setup.js
 */

import { writeFileSync, chmodSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir, platform } from 'node:os';
import { execSync } from 'node:child_process';

const __dir   = dirname(fileURLToPath(import.meta.url));
const projDir = resolve(__dir, '..');
const cliPath = resolve(__dir, 'cli.js');

// ── Find node executable ──────────────────────────────────────────────────────
function findNode() {
    try {
        const p = execSync('which node 2>/dev/null || where node 2>nul', { encoding: 'utf8' }).trim().split('\n')[0].trim();
        if (p) return p;
    } catch (_) {}
    return 'node';
}

const nodeBin = findNode();

// ── Build the artisan shell script content ────────────────────────────────────
// Use a POSIX sh script so it works in Git Bash, WSL, and Linux/macOS
const scriptContent = `#!/usr/bin/env sh
# artisan – davingm Laravel CLI
# Auto-generated by .davingm/setup.js
# Resolves project path dynamically from this script's symlink target
exec node "${cliPath.replace(/\\/g, '/')}" "$@"
`;

// ── Determine install targets ─────────────────────────────────────────────────
const home    = homedir();
const targets = [];

// ~/bin  (Git Bash default, usually in PATH already)
const userBin = resolve(home, 'bin');
targets.push(resolve(userBin, 'artisan'));

// ~/.local/bin  (Linux / WSL convention)
const localBin = resolve(home, '.local', 'bin');
targets.push(resolve(localBin, 'artisan'));

let installed = false;

for (const target of targets) {
    try {
        const dir = dirname(target);
        if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

        writeFileSync(target, scriptContent, { encoding: 'utf8' });
        chmodSync(target, 0o755);

        console.log(`[davingm] artisan installed → ${target}`);
        installed = true;
    } catch (err) {
        // Silent — try next target
    }
}

if (!installed) {
    console.warn('[davingm] Could not auto-install artisan to ~/bin or ~/.local/bin.');
    console.warn('[davingm] Run manually:');
    console.warn(`[davingm]   node "${cliPath.replace(/\\/g, '/')}" <command>`);
} else {
    console.log('[davingm] Setup complete. Run: artisan dev');
}
